services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: dagster_user
      POSTGRES_PASSWORD: dagster_password
      POSTGRES_DB: dagster_db
    volumes:
      - dagster_pgdata:/var/lib/postgresql/data
    networks:
      - dagster_network

  dagster_daemon:
    image: my-platform-base:latest
    command: dagster-daemon run
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./workspace.generated.yaml:/opt/dagster/app/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
    depends_on:
      - postgresql
    networks:
      - dagster_network
    restart: unless-stopped

  dagster_webserver:
    image: my-platform-base:latest
    command: dagster-webserver -h 0.0.0.0 -p 3000 -w workspace.yaml
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./workspace.generated.yaml:/opt/dagster/app/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
      - dagster_daemon
    networks:
      - dagster_network
    restart: unless-stopped

networks:
  dagster_network:
    driver: bridge

volumes:
  dagster_pgdata:
