[project]
name = "sywi-data-platform"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    # Minimal dependencies for dev CLI utility commands
    "dagster",
    "duckdb",
    "pyyaml>=6.0.3",
    "typer[all]>=0.9.0",
    "python-dotenv",
]

[dependency-groups]
dev = []
